### ISSUE TITLE
>90% forward surviving read pairs

### ISSUE THREAD

**Issue by HeChao7021** [usadellab/Trimmomatic#15]
Hello! I always use Trimmomatic to trim the Illumina sequencing data, It works well. But this time, the results showed that too many forward only surviving reads, and higher than 90%. I have modified many parameters, but no work. Could anyone help me?
**original command:**
trimmomatic PE -phred33 "$i"_R1.fq.gz "$i"_R2.fq.gz  "$i"_R1_paired.fq.gz "$i"_R1_unpaired.fq.gz "$i"_R2_paired.fq.gz "$i"_R2_unpaired.fq.gz ILLUMINACLIP:/disk2/users/che/miniconda2/pkgs/trimmomatic-0.39-1/share/trimmomatic-0.39-1/adapters/NexteraPE-PE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36

**result:**
TrimmomaticPE: Started with arguments:
 -phred33 147_R1.fq.gz 147_R2.fq.gz 147_R1_0paired.fq.gz 147_R1_0unpaired.fq.gz 147_R2_0paired.fq.gz 147_R2_0unpaired.fq.gz ILLUMINACLIP:/disk2/users/che/miniconda2/pkgs/trimmomatic-0.39-1/share/trimmomatic-0.39-1/adapters/NexteraPE-PE.fa:2:2:2 MINLEN:2
Using PrefixPair: 'AGATGTGTATAAGAGACAG' and 'AGATGTGTATAAGAGACAG'
Using Long Clipping Sequence: 'GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAG'
Using Long Clipping Sequence: 'TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG'
Using Long Clipping Sequence: 'CTGTCTCTTATACACATCTCCGAGCCCACGAGAC'
Using Long Clipping Sequence: 'CTGTCTCTTATACACATCTGACGCTGCCGACGA'
ILLUMINACLIP: Using 1 prefix pairs, 4 forward/reverse sequences, 0 forward only sequences, 0 reverse only sequences
Input Read Pairs: 4180392 Both Surviving: 199973 (4.78%) Forward Only Surviving: 3978732 (95.18%) Reverse Only Surviving: 136 (0.00%) Dropped: 1551 (0.04%)
TrimmomaticPE: Completed successfully

**Comment by TonyBolger** [comment]
This pattern is often caused by adapter read-through, where the read length is greater than the fragment length. In such cases, the reverse read is redundant, since it is just the forward read in reverse-complement - Trimmomatic by default keeps only the forward read in these cases. If you really want to keep both, e.g. your downstream pipeline only wants paired reads, you can pass the 'true' to the optional 'keep both' parameter to the Illumina clip step.

In this particular case, you are using very low matching thresholds for the ILLUMINACLIP step (2:2:2 vs the suggested 2:30:10), which may cause 'adapter read-through' to be detected even if there is no real evidence of it existing.

**Comment by HeChao7021** [comment]
Dear TonyBolger:    Thank for your rapidly replying! Yes, when I add 'true' to tell Trimmomatic to left both forward and reserve reads, the result is normal now. Thank you again. The reason for using 2:2:2 is that I think it is the insert reads too short to cause some many forward reads left, so I have tried to use any extreme value to have a look. But nothing helpful except using 'true' as you suggested.Here is the newest result:TrimmomaticPE: Started with arguments: -phred33 147_R1.fq.gz 147_R2.fq.gz 147_R1_0paired.fq.gz 147_R1_0unpaired.fq.gz 147_R2_0paired.fq.gz 147_R2_0unpaired.fq.gz ILLUMINACLIP:/disk2/users/che/miniconda2/pkgs/trimmomatic-0.39-1/share/trimmomatic-0.39-1/adapters/NexteraPE-PE.fa:2:30:10:8:TRUE SLIDINGWINDOW:4:15 MINLEN:30Using PrefixPair: 'AGATGTGTATAAGAGACAG' and 'AGATGTGTATAAGAGACAG'Using Long Clipping Sequence: 'GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAG'Using Long Clipping Sequence: 'TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG'Using Long Clipping Sequence: 'CTGTCTCTTATACACATCTCCGAGCCCACGAGAC'Using Long Clipping Sequence: 'CTGTCTCTTATACACATCTGACGCTGCCGACGA'ILLUMINACLIP: Using 1 prefix pairs, 4 forward/reverse sequences, 0 forward only sequences, 0 reverse only sequencesInput Read Pairs: 4180392 Both Surviving: 4055835 (97.02%) Forward Only Surviving: 32131 (0.77%) Reverse Only Surviving: 6763 (0.16%) Dropped: 85663 (2.05%)TrimmomaticPE: Completed successfullyIn addition, in this situation I wonder whether only use the forward one to align via bowtie-2 is the same to use both reads or not? -------- 原始邮件 --------发件人： TonyBolger ***@***.***>日期： 2021年9月10日周五 下午4:48收件人： usadellab/Trimmomatic ***@***.***>抄送： HeChao7021 ***@***.***>, Author ***@***.***>主    题： Re: [usadellab/Trimmomatic] >90% forward surviving read pairs (#15)
This pattern is often caused by adapter read-through, where the read length is greater than the fragment length. In such cases, the reverse read is redundant, since it is just the forward read in reverse-complement - Trimmomatic by default keeps only the forward read in these cases. If you really want to keep both, e.g. your downstream pipeline only wants paired reads, you can pass the 'true' to the optional 'keep both' parameter to the Illumina clip step.
In this particular case, you are using very low matching thresholds for the ILLUMINACLIP step (2:2:2 vs the suggested 2:30:10), which may cause 'adapter read-through' to be detected even if there is no real evidence of it existing.
