### ISSUE TITLE
trimmomatic V0.39, keepBothReads: flag or boolean?

### ISSUE THREAD

**Issue by TeiturAK** [usadellab/Trimmomatic#16]
Hi,

following your example commands in the Quick start guide at https://github.com/usadellab/Trimmomatic and http://www.usadellab.org/cms/?page=trimmomatic it seems that `keepBothReads` is a flag that is passed to trimmomatic V0.39 and not a boolean value as in the manual for earlier versions, http://www.usadellab.org/cms/uploads/supplementary/Trimmomatic/TrimmomaticManual_V0.32.pdf. 

Running trimmomatic V0.39 with `ILLUMINACLIP:TruSeq3-PE.fa:2:30:10:2:keepBothReads`  does however not produce the same results as `ILLUMINACLIP:TruSeq3-PE.fa:2:30:10:2:TRUE`. With `TRUE` there are more surviving read pairs while setting `keepBothReads` (or a random word) retains fewer. 

To me it looks like `TRUE` is the correct way of setting this parameter but in your posted examples this looks like a flag. Please advice.

**Comment by TonyBolger** [comment]
Well spotted, and you are correct - keepBothReads is the name of the flag, and its should be a boolean. I have corrected the README accordingly.

**Comment by KuechlerO** [comment]
@TonyBolger 
Kindly also consider the documentation on this page, which still displays it in the example as a flag.
