### ISSUE TITLE
encouding error on WSL 

### ISSUE THREAD

**Issue by Ezreal-XD** [usadellab/Trimmomatic#19]
I am using WSL, meeting some error like this:

(base) ez@NYM:~/Trimmomatic$ ./Trimmomatic-0.39/trimmomatic-0.39.jar
./Trimmomatic-0.39/trimmomatic-0.39.jar: line 1: $'PK\003\004': command not found
./Trimmomatic-0.39/trimmomatic-0.39.jar: line 2: $'\bN[\210N': command not found
./Trimmomatic-0.39/trimmomatic-0.39.jar: line 3M[�Ng�6��META-INF/MANIFEST.MFM��: No such file or directory
./Trimmomatic-0.39/trimmomatic-0.39.jar: line 16: syntax error near unexpected token `)'
./Trimmomatic-0.39/trimmomatic-0.39.jar: line 16:'BY<��Y�AUTHORS.jbzip2�M,)�H-W��Sp+J�K�,�PK'

**Comment by TonyBolger** [comment]
Trimmomatic is a Java-based tool - it is run using 'java -jar Trimmomatic-0.39/trimmomatic-0.39.jar' or similar
