### ISSUE TITLE
adaptor choice 

### ISSUE THREAD

**Issue by marwa38** [usadellab/Trimmomatic#2]
I contacted Illumina by asking the following 
"Recently I got my data back from the Miseq sequencer, flowcells :v3 600c 2x300 and NextraXT V2 was used set A, B and D were used as DNA library preparation kit for 16rRNA. 
 I am trying to make trimming for adaptors, barcode, indices, etc to have only the insert/fragment back for downstream analysis. 
 Could you please let me know which one should be used for the adaptors?"

Their response was as following:
"The Adapter sequence to use for Nextera XT adapter trimming is (CTGTCTCTTATACACATCT)
You can find that information in this below link as well:
https://support.illumina.com/bulletins/2016/12/what-sequences-do-i-use-for-adapter-trimming.html
This sequence can be used for both Read 1 and Read 2 if you are using paired-end sequencing run"

My query is: what is exactly the difference between what is recommended by trimmomatic to be used and what I get from Illumina
I am missing something?

So just as following:

>PrefixPE/1
CTGTCTCTTATACACATCT
>PrefixPE/2
CTGTCTCTTATACACATCT

So this is not ok to be used? 
>PrefixNX/1
AGATGTGTATAAGAGACAG
>PrefixNX/2
AGATGTGTATAAGAGACAG
>Trans1
TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG
>Trans1_rc
CTGTCTCTTATACACATCTGACGCTGCCGACGA
>Trans2
GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAG
>Trans2_rc
CTGTCTCTTATACACATCTCCGAGCCCACGAGAC

Thanks in advance
Marwa

**Comment by TonyBolger** [comment]
The PrefixNX/1 and PrefixNX/2 sequences should work as provided - these are the same as the Illumina provided sequence (CTGTCTCTTATACACATCT) but in reverse complement (Prefix sequences are handled specially by Trimmomatic, and reflect the original molecule sequence, not the sequence observed in the reads). I am not sure if the various 'Trans' sequences are needed, but they are unlikely to do harm.
