### ISSUE TITLE
keepBothReads - should it be "true" or "True"

### ISSUE THREAD

**Issue by lucygarner** [usadellab/Trimmomatic#21]
Hi,

For the keepBothReads parameter, should True have a capital letter or not? I have seen different options in the manual/GitHub page.

Best wishes,
Lucy

**Comment by TonyBolger** [comment]
Either should work. Under the covers it simply calls java.lang.Boolean.parseBoolean(), and that is documented as accepting anything equal to "true" in a case-insensitive comparison
