### ISSUE TITLE
ILLUMINACLIP trimming occurs from 5' or 3' for ?

### ISSUE THREAD

**Issue by marwa38** [usadellab/Trimmomatic#3]
Hi 

Could you please let me know from where the trimming happens (5 or 3' end) so that I could set my adpator sequence file correctly? 

I am asking about palindrome mode.

Thanks 
Marwa

**Comment by TonyBolger** [comment]
Palindrome mode applies from the 3' end of the 'other' sequence, in each case. The 'prefix' sequence of the forward read, which is upstream of the 5' end, will be searched for in reverse-complement, at the 3' end of the reverse read. The 'prefix' sequence of the reverse read, will be searched for at the 3' end of the forward read.
