### ISSUE TITLE
intallation 0.40

### ISSUE THREAD

**Issue by DavidGO464** [usadellab/Trimmomatic#48]
in the git-hub it only says that the binary file should be installed somewhere convinient...
So, Where is the binary file?
What means by convenient? 

kind regards, 

I really want to use this. TY

**Comment by ag4742** [comment]
same here 
did u find a solution?

**Comment by DininduSenanayake** [comment]
Quite confident v 0.40 is not out yet. Therefore, treat 0.39 as the latest

>So, Where is the binary file?

It's referring to .jar file which is in the [Trimmomatic-0.39.zip](https://github.com/usadellab/Trimmomatic/files/5854859/Trimmomatic-0.39.zip)  under [releases](https://github.com/usadellab/Trimmomatic/releases)

**Comment by DavidGO464** [comment]
> 

yes, it seems that v 0.40 is not out yet. 0.39 works fine. It hink I install it using pip install. it works fine
